#ifndef __MAIN_H__
#define __MAIN_H__

#include "stm32f4xx.h" 
#include "pin_ctrl.h"
#include "key.h"
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include "systick_conf.h"
#include "nvic_conf.h"
#include "lv_port_disp.h"
#include "adc.h"
#include "fatfs.h"
#include "fontupd.h"
#include "malloc.h"
#include "rtc_clock.h"
#include "es9018k2m.h"
#include "music.h"
#include "rng.h"
#include "sdio_sdcard.h"
#include "w25q128.h"
#include "usbd_cdc_conf.h"
#include "usbd_msc_conf.h"
#include "usbd_uac1_conf.h"
#include "usbd_uac2_conf.h"
#include "usbd_display_conf.h"
#include "usbh_core.h"
#include "defines.h"
#include "variables.h"
#include "lv_port_indev.h"
#include "flashdb.h"
#include "fal.h"
#include "task_manager.h"
#include "usbd_hid_conf.h"
#include "iwdg.h"

#endif
